name: continuos-integration
on: ["push"]
jobs:
   ci:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: golang setup
         uses: actions/setup-go@v4
         with:
           go-version: 1.22.2
       - name: build
         run: go build -v ./...
       - name: test
         run: go test ./... -v -cover
       - name: lint
         uses: golangci/golangci-lint-action@v4
         with:
           version: v1.54
